from datetime import date

import os

DATABASE="US_VISA"
RAW_DATA_COLLECTION="raw"
MONGODB_URL_KEY="MONGO_URL"
PIPELINE="usvisa"
ARTIFACT_DIR="artifact"
MODEL_FILE="model.pkl"
TARGET_COLUMN="case_status"
CURRENT_YEAR=date.today().year
PREPROCESSING_FILE="preprocessing.pkl"
RAW_DATA_FILE="raw.csv"
TRAIN_DATA_FILE="train.csv"
TEST_DATA_FILE="test.csv"
SCHEMA_FILE=os.path.join("config", "schema.yaml")

DATA_INGESTION_DIR="data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR="feature_store"
DATA_INGESTION_INGESTED_DIR="ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO=0.2

DATA_VALIDATION_DIR="data_validation"
DATA_VALIDATION_DRIFT_REPORT_DIR="drift_report"
DATA_VALIDATION_DRIFT_REPORT_FILE="report.yaml"

DATA_TRANSFORMATION_DIR = "data_transformation"
DATA_TRANSFORMATION_TRANSFORMED_DATA_DIR = "transformed"
DATA_TRANSFORMATION_TRANSFORMED_OBJECT_DIR = "transformed_object"

MODEL_TRAINER_DIR = "model_trainer"
MODEL_TRAINER_MODEL_DIR = "trained_model"
MODEL_TRAINER_MODEL_FILE = "model.pkl"
MODEL_TRAINER_EXPECTED_ACCURACY = 0.6
MODEL_TRAINER_MODEL_CONFIG_FILE = os.path.join("config", "model.yaml")

AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_REGION_NAME = "ap-south-1"

MODEL_EVALUATION_CHANGE_THRESHOLD_SCORE: float = 0.02
MODEL_BUCKET_NAME = "uvisaapprovalmodel"
MODEL_PUSHER_S3_KEY = "model-registry"

APP_HOST = "0.0.0.0"
APP_PORT = "8080"